### ISSUE TITLE
Show date and time information for builds from the same revision

### ISSUE THREAD

**Issue by jdm** [servo/buildbotstatus#8]
The git revision alone doesn't always provide enough context to easily tell which build you're looking at. Adding date and time information would be helpful.

**Comment by ferjm** [comment]
We already store the [start and end dates](https://github.com/servo/buildbotstatus/blob/master/app/scripts/build.js#L27) info for each build, so this should be just a matter of [showing](https://github.com/servo/buildbotstatus/blob/master/app/scripts/ui.js#L66) this info in the UI.

**Comment by DanielChanJA** [comment]
Hi I'm interested in putting out a fix for this @highfive: assign me

**Comment by ferjm** [comment]
@DanielChanJA how are things going with this issue? Let me know if you need any help.

**Comment by DanielChanJA** [comment]
Hey @ferjm sorry about the delay, been caught up schoolwork. I just started taking a look at this, not sure which date format you want the times in.

I'm still in the process of cleaning it up, need to expand the width of the table cells so it doesn't look weird with the current text-wrapping.

Terrible default toString() of the dates.
<img width="1191" alt="screen shot 2018-02-13 at 4 40 54 am" src="https://user-images.githubusercontent.com/8815916/36143235-88005c8a-1078-11e8-854f-f781a1606833.png">

Upon further inspection the time on the build page GMT +0 time, should I standardize and make it GMT +0 here as well?

**Comment by ferjm** [comment]
No worries at all! This is definitely not something urgent, I just wanted to check that you had everything you needed to progress with this task.

To reduce UI clutter and visual overload I would simply show the start date (and maybe the end date too to differentiate finished from in-progress builds) of the first build instead of the start and end dates of each separate build. We can show this info along with the commit hash.

Regarding the date format, I would go with `Feb 10 2018 09:53:01`. Ideally we should convert the times to the user's timezone, but we can just leave them in GMT+0 for now and file a follow up task to deal with this.

Thank you for working on this!

**Comment by DanielChanJA** [comment]
Understood, I'll look to make the adjustments and will have it ready to be reviewed in the next couple of days :)

**Comment by jdm** [comment]
@DanielChanJA How's it going? :)

**Comment by DanielChanJA** [comment]
@jdm Sorry about it, I've been caught up with midterms and assignments. I just need to make the adjustments from the feedback.

**Comment by DanielChanJA** [comment]
@ferjm Let me know your thoughts on this, currently it hides the "Last build ended at: ..." if there's any build that is in progress.

![rasd1](https://user-images.githubusercontent.com/8815916/37190522-4d177a0a-2328-11e8-8b9d-b39e8fd556ec.png)
![rasd2](https://user-images.githubusercontent.com/8815916/37190527-4f86aebe-2328-11e8-86a0-c4f74dac79ec.png)

**Comment by ferjm** [comment]
Looks good! Just one comment: instead of simply hiding "Last build ended at: ...", it may be worth to add an "In progress" label. Thank you @DanielChanJA!

**Comment by CYBAI** [comment]
@ferjm 
Due to #17 merged, I think this issue can be closed 😆?

**Comment by ferjm** [comment]
Right! Thanks for the reminder :)
